apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook
spec:
  interval: 1m
  chart:
    spec:
      chart: rook-ceph
      version: 1.14.4
      sourceRef:
        kind: HelmRepository
        name: rook-release
      interval: 5m
  values: 