---
- hosts: '{{ servers | mandatory }}'
  pre_tasks:
    # containerd dependency
    - name: install gnupg2
      apt: 
        name: gnupg2
        state: present
        update_cache: yes
    - name: load br_netfilter
      modprobe:
        name: br_netfilter
        state: present
    - name: set sysctl rules
      ansible.posix.sysctl:
        name: '{{ item }}'
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      loop:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward
  roles:
    - role: geerlingguy.containerd
    - role: kubernetes
