apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hcloud-csi
spec:
  interval: 1m
  chart:
    spec:
      chart: hcloud-csi
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: hcloud
      interval: 5m
  values:
    replicaCount: 1
    controller:
      hcloudToken:
        existingSecret:
          name: hcloud-token
    storageClasses:
      - name: hcloud-volumes
        defaultStorageClass: true
        reclaimPolicy: Delete