apiVersion: v1
data:
    token: ENC[AES256_GCM,data:El4jZHSohioOo1QGohQRir9ME7Sb9GgkzsbWEMYBjJFHkV9II+B/emF2r4mWaytfgpfxG1JTU8sppdayGYSxzuKHeyO+4MYuuSzWYQQMJngiRADSobL9tg==,iv:k5s7D2usysCtpWAw5s/whAO2yxPo0jV8/Zhh3HbMiPs=,tag:6HxXB4npNaeExnuN/D7skw==,type:str]
kind: Secret
metadata:
    name: hcloud-token
    namespace: cloud-provider
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng398qsp5vfcwtptfcacf5l77wmvqqjkezmkyenz7zk85h2fk36sj2fdfa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeDI5ZzlXYkFrV3Q0Z2VJ
            UTduVkw5K2ZTZ1E2ZUYvcm9oUE1zeWpLaDJrCmRNL3g1QnRSblFTQTZzWnR3ZVBk
            RTFIR09WWEpJRFEyTkh3bi85MXV1SGMKLS0tIDlFVk42MmVXeW1JbUdzQUVvMmcr
            YlZidElIRjBUMCtDZDd2WEJVUGkzUHMK+8jnv7XVTlmLFkwGHUVGUVCqgLQl4t2K
            CFwZGayNXmr1z868KvbQCzdEYOYi8KdxP+ePIslyj8sDr6Yl0Ryv4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1csj946q0xtcwwf4d9nxg3zqyy9w5tynlzh20mp267mqhshyar97qw0fkre
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWkpWYW9JN2k3My9Va3lk
            UjVEWGRJamJjOFhFL1JuN1hKUU05cHdIaW00CnU4U2RxY1VvbXczSlQ1VDlkSG5N
            Q2hZZGNscXh3c1RMSElxRXJ3RUNDTW8KLS0tIDM0K0s3dFQ2L3NQTlpqaXJEeG4z
            R3pCbk0veGxmT1p6aEh5QzRudHJWSHMKgonNuTRIHM3ckhYekVzpLYfRAc/21Awl
            lL5+z0hatb0/CMm6so1rghb3dE6o0M4/EZpkX7fIgtYMzaGYsq5oDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hdvlellfzyeefleuz252kaalnqvmuus8v6cy0l9m4cdreapnscsrv6py3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNlg5NWYxS2oveVdtdG5x
            SXhuMWNnRFUxOFAwdUtwdkp4ZW84Y0VuTWlvCnIrbHBVR1l2Q1NGck1ZRUNRQmxF
            UHRrbHBDQm5hS2pYbWlYOTJJQVRtRzQKLS0tIHUvQ1kyejh2U0I1U1FneEx6aFFz
            cTB5czQ4TUUrNDZ3VGk0Z2lnOC9iTjQKX1Z9VZRXUg8XcMKggaZajrMG1++7Ij42
            0wOYevevy1uaJK0awyO23N3IPRX9cG8C7a+71UdJxPdWdH8hwqQDBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-10T21:43:26Z"
    mac: ENC[AES256_GCM,data:jpec189KUNGEEDbm2zf6xaEBqRAFnlpQFA1KggQ4ewf+I+mL7PtxQoy9nE7aoALjsbLW6rU6zSoVG041hi3fXvg0ZOgdFLUcr6zCf1und6194Sg+tUxSYls/IyytTbAg7FDNTrfQtRpIzPatxaZLIn9SF3q2aPS7IZqfgvt3FP8=,iv:E5oPHsZcRWL7JiYS81KuTnlFXeztCZsxh33x0niNbvo=,tag:bECVb5WbgtIspZruVDqLrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
