---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: app1-euc
spec:
  interval: 5m
  url: oci://ghcr.io/freggy/infra/flux
  ref:
    tag: latest
  secretRef:
    name: ghcr-auth
