apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:C/KzX8Tv23DHDgAtj0cC31jUtQVQLNL8K6h30Kvvl4K3AXXNjAXDpbwp34E06LuyzY39EjA+uu+4Pqo/4oBEhIwR3R9mQuQBc77kcsAHNKma7fLQ7QgZqssQ4rD6+AygXV2inA==,iv:CVlz10wFO5p9JScNBee9lzhzS85hIWqe7y0kEBC19Vc=,tag:iwvJqNHLJnrlVi/AjdIFVQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-cluster-key
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng398qsp5vfcwtptfcacf5l77wmvqqjkezmkyenz7zk85h2fk36sj2fdfa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SjZRZFplazJheGtSTUt5
            QXBnMTVyUG81T01IbUxqS2tmcnB1cER3d0hzCkxKbko5VTd2cUh5YnVRTW9NUkJI
            U3ovU3VtUmREZ1JqbVJ5Q2NSWFhGb1kKLS0tIDU0di9wSzBPRll2OU41M0xJSHJu
            YlppTzNnYXM4WnBzNGNMWjUzQzFYSUUKGkxb/B+F5VVscdNbfoFtlOUGhvi0EK1b
            46w7lYbu6yx19vNZyBc0pu86vdQHTaPGUZERBA3egb5zoVa77z4VaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1csj946q0xtcwwf4d9nxg3zqyy9w5tynlzh20mp267mqhshyar97qw0fkre
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeWxOc3ZOZHcrL1VmSVdG
            VUtVbG5NQ1FqVHQzMklGWTNmejdaWklVbUVzCjlkTnRUNk1WOEdpOUd2Q1BZTldV
            VGc1Q2p2M3VTd3NPSk5vMllZZlNEUVEKLS0tIExtL2JMdWJ6WTZMOVVRS3NXUWM0
            MzZrWGh4VTljMDMrUmJqckhKNEZOWW8K8jwnyLkmB2wfgtSG/GUTwHhPeWNb6pF3
            xCefo7EQpRkLe9kkUFQeZRjSvwWPeZQ2ppQaahWvmpp9Vjbda0kBag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hdvlellfzyeefleuz252kaalnqvmuus8v6cy0l9m4cdreapnscsrv6py3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMEpCRGtFNDJkOU5ENUVF
            NmdUdzc4Umw2ZDg0c1hsSHFGSlpnbm9aRDBvCjJEYVBocklIUGJiWWhwNS9LUUVw
            WkpDMW5NL293eGxrNlVvcVFTUlM3ckUKLS0tIDJrUC8ybWx3RjU4UFZmWmExT1dy
            cS9McGRYL1AxZHhsL1JNa283WmJkbjgKbmpfjVRD460JyNUOOQsC5YfqZmar647M
            48fYfB7UArCyUuqNsJR/cVWmPASQwl8gPVifTmPVdnKMMxgm0QSrAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-10T22:38:57Z"
    mac: ENC[AES256_GCM,data:g7phrj/YfYHSzWDOSP+NSaLEZa2Qto/8Aeo/zpvmlS5n9eY6IfD7Te4K55C/RMLMRLvqOqP7qyMew9AZAupl7gv230vZbStv6sK/ogpaTXsEzruEyXXUjCLDZzuGFZ3uBVzKC9pxUCmcT7lBOx5kM8H8siLrQJcCaS46lkBRcX4=,iv:ZQ62qUBm2BN0s55PlsH064UUhIzPJ6Ed3/1tYHdzymY=,tag:2ECncyO6418O69QH8SPIBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1